baseURL = 'https://sezaki02.github.io/phalacrocorax/'
languageCode = 'ja'
publishDir = "docs"
canonifyurls = true
theme = 'holy'
title = 'Phalacrocorax'

[menu]
 [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 10
